name: Build

on:
  schedule:
    - cron: '30 10 * * 5'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest    
    steps:
      - name: Check new version
        # if: github.event.schedule == '30 10 * * 5'
        run: |
          LAST_VERSION=$(curl -s 'https://registry.hub.docker.com/v2/repositories/litded/youtrack-arm/tags/' | jq '."results"[]["name"]' | head -1 | sed 's/"//g')
          DIST_VERSION=$(curl -s 'https://registry.hub.docker.com/v2/repositories/jetbrains/youtrack/tags/' | jq '."results"[]["name"]' | head -1 | sed 's/"//g')
          if [[ $DIST_VERSION != $LAST_VERSION ]]: then echo "$DIST_VERSION" > last_version.txt; else: exit 1;  fi
          
  docker:
    needs: check
    runs-on: self-hosted
    steps:

      - name: Get code
        uses: actions/checkout@v4

      - name: Building a new tag
        run: |
          DIST_VERSION=$(curl -s 'https://registry.hub.docker.com/v2/repositories/jetbrains/youtrack/tags/' | jq '."results"[]["name"]' | head -1 | sed 's/"//g')
          wget "https://download-cdn.jetbrains.com/charisma/youtrack-$DIST_VERSION.zip"
          unzip "youtrack-$DIST_VERSION.zip" && mv "youtrack-$DIST_VERSION/" youtrack && rm -f "youtrack-$DIST_VERSION.zip"
          docker build --build-arg DIST_VERSION=$DIST_VERSION . --tag litded/youtrack-arm:$DIST_VERSION
          docker push litded/youtrack-arm:$DIST_VERSION
          docker rm litded/youtrack-arm:$DIST_VERSION
